### ISSUE TITLE
i cant download

### ISSUE THREAD

**Issue by ducttapey** [envyclient/issues#24]
so basicly when i try to download it, it says corrupted files.
![image](https://user-images.githubusercontent.com/57417186/68244592-0bc11700-000d-11ea-8d82-afe3ff4aec57.png)

**Comment by haq** [comment]
You are trying to just run the jar file.

Please watch [https://www.youtube.com/watch?v=4PQTDTmbUaA](this) on how to install Envy Client.

**Comment by ducttapey** [comment]
its not downloading a [.exe] file. its only downloading a [.jar] file.

**Comment by haq** [comment]
You should watch the video. It never downloads a [.exe] file.

I think you are referring to the Minecraft installer. You should be able to just visit the Minecraft website and download the installer.
