### ISSUE TITLE
Can't get the console to pop up.

### ISSUE THREAD

**Issue by ToasterWifi** [envyclient/issues#25]
I cannot get the console/menu to pop up. I try press the tilde key to open up the console, it does not work. Please let me know if you know what could be causing this. Thank you!

P.S I'm currently using latest version for me 4.2 and  in the bottom left corner of where there's singleplayer and multiplayer it says "There's currently 1 issue"

**Comment by haq** [comment]
Try pressing the "Right Shift" key on your keyboard.

**Comment by ToasterWifi** [comment]
IT worked thank you!
